// Country / nationality codes accepted by SIBA (ICAO Doc 9303 table published at
// https://siba.ssi.gov.pt/ajuda/modos-de-envio/lista-de-paises/ ).
// NOTE: SIBA uses the ICAO code "D" for Germany (not "DEU") and "RKS" for Kosovo.
// iso2 is only used by the browser to show localized names via Intl.DisplayNames.
export interface Country { code: string; iso2: string; pt: string; en: string }

export const COUNTRIES: Country[] = [
  { code: "AFG", iso2: "AF", pt: "Afeganistão", en: "Afghanistan" },
  { code: "ALB", iso2: "AL", pt: "Albânia", en: "Albania" },
  { code: "DZA", iso2: "DZ", pt: "Argélia", en: "Algeria" },
  { code: "AND", iso2: "AD", pt: "Andorra", en: "Andorra" },
  { code: "AGO", iso2: "AO", pt: "Angola", en: "Angola" },
  { code: "ATG", iso2: "AG", pt: "Antígua e Barbuda", en: "Antigua and Barbuda" },
  { code: "ARG", iso2: "AR", pt: "Argentina", en: "Argentina" },
  { code: "ARM", iso2: "AM", pt: "Arménia", en: "Armenia" },
  { code: "AUS", iso2: "AU", pt: "Austrália", en: "Australia" },
  { code: "AUT", iso2: "AT", pt: "Áustria", en: "Austria" },
  { code: "AZE", iso2: "AZ", pt: "Azerbaijão", en: "Azerbaijan" },
  { code: "BHS", iso2: "BS", pt: "Bahamas", en: "Bahamas" },
  { code: "BHR", iso2: "BH", pt: "Barém", en: "Bahrain" },
  { code: "BGD", iso2: "BD", pt: "Bangladesh", en: "Bangladesh" },
  { code: "BRB", iso2: "BB", pt: "Barbados", en: "Barbados" },
  { code: "BLR", iso2: "BY", pt: "Bielorrússia", en: "Belarus" },
  { code: "PLW", iso2: "PW", pt: "Palau", en: "Palau" },
  { code: "BEL", iso2: "BE", pt: "Bélgica", en: "Belgium" },
  { code: "BLZ", iso2: "BZ", pt: "Belize", en: "Belize" },
  { code: "BEN", iso2: "BJ", pt: "Benim", en: "Benin" },
  { code: "BMU", iso2: "BM", pt: "Bermudas", en: "Bermuda" },
  { code: "BTN", iso2: "BT", pt: "Butão", en: "Bhutan" },
  { code: "BOL", iso2: "BO", pt: "Bolívia", en: "Bolivia" },
  { code: "BIH", iso2: "BA", pt: "Bósnia e Herzegovina", en: "Bosnia and Herzegovina" },
  { code: "BWA", iso2: "BW", pt: "Botswana", en: "Botswana" },
  { code: "BRA", iso2: "BR", pt: "Brasil", en: "Brazil" },
  { code: "BRN", iso2: "BN", pt: "Brunei Darussalam", en: "Brunei Darussalam" },
  { code: "BGR", iso2: "BG", pt: "Bulgária", en: "Bulgaria" },
  { code: "BFA", iso2: "BF", pt: "Burkina Faso", en: "Burkina Faso" },
  { code: "MMR", iso2: "MM", pt: "Myanmar (Birmânia)", en: "Myanmar" },
  { code: "BDI", iso2: "BI", pt: "Burundi", en: "Burundi" },
  { code: "KHM", iso2: "KH", pt: "Camboja", en: "Cambodia" },
  { code: "CMR", iso2: "CM", pt: "Camarões", en: "Cameroon" },
  { code: "CAN", iso2: "CA", pt: "Canadá", en: "Canada" },
  { code: "CPV", iso2: "CV", pt: "Cabo Verde", en: "Cape Verde" },
  { code: "CAF", iso2: "CF", pt: "República Centro-Africana", en: "Central African Republic" },
  { code: "TCD", iso2: "TD", pt: "Chade", en: "Chad" },
  { code: "CHL", iso2: "CL", pt: "Chile", en: "Chile" },
  { code: "CHN", iso2: "CN", pt: "China", en: "China" },
  { code: "COL", iso2: "CO", pt: "Colômbia", en: "Colombia" },
  { code: "COM", iso2: "KM", pt: "União das Comores", en: "Comoros" },
  { code: "COG", iso2: "CG", pt: "Congo", en: "Congo" },
  { code: "COK", iso2: "CK", pt: "Ilhas Cook", en: "Cook Islands" },
  { code: "CRI", iso2: "CR", pt: "Costa Rica", en: "Costa Rica" },
  { code: "HRV", iso2: "HR", pt: "Croácia", en: "Croatia" },
  { code: "CZE", iso2: "CZ", pt: "Chéquia (República Checa)", en: "Czech Republic" },
  { code: "CUB", iso2: "CU", pt: "Cuba", en: "Cuba" },
  { code: "CYP", iso2: "CY", pt: "Chipre", en: "Cyprus" },
  { code: "DNK", iso2: "DK", pt: "Dinamarca", en: "Denmark" },
  { code: "DJI", iso2: "DJ", pt: "Jibuti", en: "Djibouti" },
  { code: "DMA", iso2: "DM", pt: "Dominica", en: "Dominica" },
  { code: "DOM", iso2: "DO", pt: "República Dominicana", en: "Dominican Republic" },
  { code: "TLS", iso2: "TL", pt: "Timor-Leste", en: "Timor-Leste" },
  { code: "ECU", iso2: "EC", pt: "Equador", en: "Ecuador" },
  { code: "EGY", iso2: "EG", pt: "Egito", en: "Egypt" },
  { code: "SLV", iso2: "SV", pt: "El Salvador", en: "El Salvador" },
  { code: "GNQ", iso2: "GQ", pt: "Guiné Equatorial", en: "Equatorial Guinea" },
  { code: "ERI", iso2: "ER", pt: "Eritreia", en: "Eritrea" },
  { code: "EST", iso2: "EE", pt: "Estónia", en: "Estonia" },
  { code: "ETH", iso2: "ET", pt: "Etiópia", en: "Ethiopia" },
  { code: "FJI", iso2: "FJ", pt: "Ilhas Fiji", en: "Fiji" },
  { code: "FIN", iso2: "FI", pt: "Finlândia", en: "Finland" },
  { code: "FRA", iso2: "FR", pt: "França", en: "France" },
  { code: "GAB", iso2: "GA", pt: "Gabão", en: "Gabon" },
  { code: "GMB", iso2: "GM", pt: "Gâmbia", en: "Gambia" },
  { code: "GEO", iso2: "GE", pt: "Geórgia", en: "Georgia" },
  { code: "D", iso2: "DE", pt: "Alemanha", en: "Germany" },
  { code: "GHA", iso2: "GH", pt: "Gana", en: "Ghana" },
  { code: "GRC", iso2: "GR", pt: "Grécia", en: "Greece" },
  { code: "GRD", iso2: "GD", pt: "Granada", en: "Grenada" },
  { code: "GUM", iso2: "GU", pt: "Guam", en: "Guam" },
  { code: "GTM", iso2: "GT", pt: "Guatemala", en: "Guatemala" },
  { code: "GIN", iso2: "GN", pt: "Guiné", en: "Guinea" },
  { code: "GNB", iso2: "GW", pt: "Guiné-Bissau", en: "Guinea-Bissau" },
  { code: "GUY", iso2: "GY", pt: "Guiana", en: "Guyana" },
  { code: "HTI", iso2: "HT", pt: "Haiti", en: "Haiti" },
  { code: "HND", iso2: "HN", pt: "Honduras", en: "Honduras" },
  { code: "HKG", iso2: "HK", pt: "Hong Kong", en: "Hong Kong" },
  { code: "HUN", iso2: "HU", pt: "Hungria", en: "Hungary" },
  { code: "ISL", iso2: "IS", pt: "Islândia", en: "Iceland" },
  { code: "IND", iso2: "IN", pt: "Índia", en: "India" },
  { code: "IDN", iso2: "ID", pt: "Indonésia", en: "Indonesia" },
  { code: "IRN", iso2: "IR", pt: "Irão", en: "Iran" },
  { code: "IRQ", iso2: "IQ", pt: "Iraque", en: "Iraq" },
  { code: "IRL", iso2: "IE", pt: "Irlanda", en: "Ireland" },
  { code: "ISR", iso2: "IL", pt: "Israel", en: "Israel" },
  { code: "ITA", iso2: "IT", pt: "Itália", en: "Italy" },
  { code: "CIV", iso2: "CI", pt: "Costa do Marfim", en: "Côte d'Ivoire" },
  { code: "JAM", iso2: "JM", pt: "Jamaica", en: "Jamaica" },
  { code: "JPN", iso2: "JP", pt: "Japão", en: "Japan" },
  { code: "JOR", iso2: "JO", pt: "Jordânia", en: "Jordan" },
  { code: "KAZ", iso2: "KZ", pt: "Cazaquistão", en: "Kazakhstan" },
  { code: "KEN", iso2: "KE", pt: "Quénia", en: "Kenya" },
  { code: "KIR", iso2: "KI", pt: "Kiribati", en: "Kiribati" },
  { code: "PRK", iso2: "KP", pt: "Coreia do Norte", en: "North Korea" },
  { code: "KOR", iso2: "KR", pt: "Coreia do Sul", en: "South Korea" },
  { code: "RKS", iso2: "XK", pt: "Kosovo", en: "Kosovo" },
  { code: "KWT", iso2: "KW", pt: "Kuwait", en: "Kuwait" },
  { code: "KGZ", iso2: "KG", pt: "Quirguizistão", en: "Kyrgyzstan" },
  { code: "LAO", iso2: "LA", pt: "Laos", en: "Laos" },
  { code: "LVA", iso2: "LV", pt: "Letónia", en: "Latvia" },
  { code: "LBN", iso2: "LB", pt: "Líbano", en: "Lebanon" },
  { code: "LSO", iso2: "LS", pt: "Lesoto", en: "Lesotho" },
  { code: "LBR", iso2: "LR", pt: "Libéria", en: "Liberia" },
  { code: "LBY", iso2: "LY", pt: "Líbia", en: "Libya" },
  { code: "LIE", iso2: "LI", pt: "Liechtenstein", en: "Liechtenstein" },
  { code: "LTU", iso2: "LT", pt: "Lituânia", en: "Lithuania" },
  { code: "LUX", iso2: "LU", pt: "Luxemburgo", en: "Luxembourg" },
  { code: "MAC", iso2: "MO", pt: "Macau", en: "Macao" },
  { code: "MKD", iso2: "MK", pt: "Macedónia do Norte", en: "North Macedonia" },
  { code: "MDG", iso2: "MG", pt: "Madagáscar", en: "Madagascar" },
  { code: "MWI", iso2: "MW", pt: "Malawi", en: "Malawi" },
  { code: "MYS", iso2: "MY", pt: "Malásia", en: "Malaysia" },
  { code: "MDV", iso2: "MV", pt: "Maldivas", en: "Maldives" },
  { code: "MLI", iso2: "ML", pt: "Mali", en: "Mali" },
  { code: "MLT", iso2: "MT", pt: "Malta", en: "Malta" },
  { code: "MHL", iso2: "MH", pt: "Ilhas Marshall", en: "Marshall Islands" },
  { code: "MRT", iso2: "MR", pt: "Mauritânia", en: "Mauritania" },
  { code: "MUS", iso2: "MU", pt: "Ilhas Maurícias", en: "Mauritius" },
  { code: "MYT", iso2: "YT", pt: "Mayotte", en: "Mayotte" },
  { code: "MEX", iso2: "MX", pt: "México", en: "Mexico" },
  { code: "FSM", iso2: "FM", pt: "Micronésia", en: "Micronesia" },
  { code: "MDA", iso2: "MD", pt: "Moldávia", en: "Moldova" },
  { code: "MCO", iso2: "MC", pt: "Mónaco", en: "Monaco" },
  { code: "MNG", iso2: "MN", pt: "Mongólia", en: "Mongolia" },
  { code: "MSR", iso2: "MS", pt: "Monserrate", en: "Montserrat" },
  { code: "MNE", iso2: "ME", pt: "Montenegro", en: "Montenegro" },
  { code: "MAR", iso2: "MA", pt: "Marrocos", en: "Morocco" },
  { code: "MOZ", iso2: "MZ", pt: "Moçambique", en: "Mozambique" },
  { code: "NAM", iso2: "NA", pt: "Namíbia", en: "Namibia" },
  { code: "NRU", iso2: "NR", pt: "Nauru", en: "Nauru" },
  { code: "NPL", iso2: "NP", pt: "Nepal", en: "Nepal" },
  { code: "NLD", iso2: "NL", pt: "Países Baixos", en: "Netherlands" },
  { code: "NCL", iso2: "NC", pt: "Nova Caledónia", en: "New Caledonia" },
  { code: "NZL", iso2: "NZ", pt: "Nova Zelândia", en: "New Zealand" },
  { code: "NIC", iso2: "NI", pt: "Nicarágua", en: "Nicaragua" },
  { code: "NER", iso2: "NE", pt: "Níger", en: "Niger" },
  { code: "NGA", iso2: "NG", pt: "Nigéria", en: "Nigeria" },
  { code: "NIU", iso2: "NU", pt: "Niue", en: "Niue" },
  { code: "NOR", iso2: "NO", pt: "Noruega", en: "Norway" },
  { code: "OMN", iso2: "OM", pt: "Omã", en: "Oman" },
  { code: "PAK", iso2: "PK", pt: "Paquistão", en: "Pakistan" },
  { code: "PSE", iso2: "PS", pt: "Palestina", en: "Palestine" },
  { code: "PAN", iso2: "PA", pt: "Panamá", en: "Panama" },
  { code: "PNG", iso2: "PG", pt: "Papua-Nova Guiné", en: "Papua New Guinea" },
  { code: "PRY", iso2: "PY", pt: "Paraguai", en: "Paraguay" },
  { code: "PER", iso2: "PE", pt: "Peru", en: "Peru" },
  { code: "PHL", iso2: "PH", pt: "Filipinas", en: "Philippines" },
  { code: "POL", iso2: "PL", pt: "Polónia", en: "Poland" },
  { code: "PRT", iso2: "PT", pt: "Portugal", en: "Portugal" },
  { code: "PRI", iso2: "PR", pt: "Porto Rico", en: "Puerto Rico" },
  { code: "QAT", iso2: "QA", pt: "Catar", en: "Qatar" },
  { code: "COD", iso2: "CD", pt: "República Democrática do Congo", en: "Democratic Republic of the Congo" },
  { code: "REU", iso2: "RE", pt: "Reunião", en: "Réunion" },
  { code: "ROU", iso2: "RO", pt: "Roménia", en: "Romania" },
  { code: "RUS", iso2: "RU", pt: "Rússia", en: "Russia" },
  { code: "RWA", iso2: "RW", pt: "Ruanda", en: "Rwanda" },
  { code: "STP", iso2: "ST", pt: "São Tomé e Príncipe", en: "São Tomé and Príncipe" },
  { code: "VCT", iso2: "VC", pt: "São Vicente e Granadinas", en: "Saint Vincent and the Grenadines" },
  { code: "WSM", iso2: "WS", pt: "Samoa", en: "Samoa" },
  { code: "SMR", iso2: "SM", pt: "São Marino", en: "San Marino" },
  { code: "SAU", iso2: "SA", pt: "Arábia Saudita", en: "Saudi Arabia" },
  { code: "SEN", iso2: "SN", pt: "Senegal", en: "Senegal" },
  { code: "SRB", iso2: "RS", pt: "Sérvia", en: "Serbia" },
  { code: "SYC", iso2: "SC", pt: "Seychelles", en: "Seychelles" },
  { code: "SLE", iso2: "SL", pt: "Serra Leoa", en: "Sierra Leone" },
  { code: "SGP", iso2: "SG", pt: "Singapura", en: "Singapore" },
  { code: "SVK", iso2: "SK", pt: "Eslováquia", en: "Slovakia" },
  { code: "SVN", iso2: "SI", pt: "Eslovénia", en: "Slovenia" },
  { code: "SLB", iso2: "SB", pt: "Ilhas Salomão", en: "Solomon Islands" },
  { code: "SOM", iso2: "SO", pt: "Somália", en: "Somalia" },
  { code: "ZAF", iso2: "ZA", pt: "África do Sul", en: "South Africa" },
  { code: "SSD", iso2: "SS", pt: "República do Sudão do Sul", en: "South Sudan" },
  { code: "ESP", iso2: "ES", pt: "Espanha", en: "Spain" },
  { code: "LKA", iso2: "LK", pt: "Sri Lanka", en: "Sri Lanka" },
  { code: "KNA", iso2: "KN", pt: "São Cristóvão e Nevis", en: "Saint Kitts and Nevis" },
  { code: "LCA", iso2: "LC", pt: "Santa Lúcia", en: "Saint Lucia" },
  { code: "SDN", iso2: "SD", pt: "Sudão", en: "Sudan" },
  { code: "SUR", iso2: "SR", pt: "Suriname", en: "Suriname" },
  { code: "SWZ", iso2: "SZ", pt: "Essuatíni (Suazilândia)", en: "Eswatini (Swaziland)" },
  { code: "SWE", iso2: "SE", pt: "Suécia", en: "Sweden" },
  { code: "CHE", iso2: "CH", pt: "Suíça", en: "Switzerland" },
  { code: "SYR", iso2: "SY", pt: "Síria", en: "Syria" },
  { code: "TWN", iso2: "TW", pt: "Taiwan", en: "Taiwan" },
  { code: "TJK", iso2: "TJ", pt: "Tajiquistão", en: "Tajikistan" },
  { code: "TZA", iso2: "TZ", pt: "Tanzânia", en: "Tanzania" },
  { code: "THA", iso2: "TH", pt: "Tailândia", en: "Thailand" },
  { code: "TGO", iso2: "TG", pt: "Togo", en: "Togo" },
  { code: "TON", iso2: "TO", pt: "Tonga", en: "Tonga" },
  { code: "TTO", iso2: "TT", pt: "Trindade e Tobago", en: "Trinidad and Tobago" },
  { code: "TUN", iso2: "TN", pt: "Tunísia", en: "Tunisia" },
  { code: "TUR", iso2: "TR", pt: "Turquia", en: "Türkiye (Turkey)" },
  { code: "TKM", iso2: "TM", pt: "Turquemenistão", en: "Turkmenistan" },
  { code: "TUV", iso2: "TV", pt: "Tuvalu", en: "Tuvalu" },
  { code: "UGA", iso2: "UG", pt: "Uganda", en: "Uganda" },
  { code: "UKR", iso2: "UA", pt: "Ucrânia", en: "Ukraine" },
  { code: "ARE", iso2: "AE", pt: "Emirados Árabes Unidos", en: "United Arab Emirates" },
  { code: "GBR", iso2: "GB", pt: "Reino Unido", en: "United Kingdom" },
  { code: "URY", iso2: "UY", pt: "Uruguai", en: "Uruguay" },
  { code: "USA", iso2: "US", pt: "Estados Unidos da América", en: "United States of America" },
  { code: "UZB", iso2: "UZ", pt: "Uzbequistão", en: "Uzbekistan" },
  { code: "VUT", iso2: "VU", pt: "Vanuatu", en: "Vanuatu" },
  { code: "VAT", iso2: "VA", pt: "Santa Sé (Vaticano)", en: "Vatican City (Holy See)" },
  { code: "VEN", iso2: "VE", pt: "Venezuela", en: "Venezuela" },
  { code: "VNM", iso2: "VN", pt: "Vietname", en: "Vietnam" },
  { code: "YEM", iso2: "YE", pt: "Iémen", en: "Yemen" },
  { code: "ZMB", iso2: "ZM", pt: "Zâmbia", en: "Zambia" },
  { code: "ZWE", iso2: "ZW", pt: "Zimbabwe", en: "Zimbabwe" },
];

export const COUNTRY_CODES: ReadonlySet<string> = new Set(COUNTRIES.map((c) => c.code));
export const PORTUGAL = "PRT";

export function isCountryCode(code: unknown): code is string {
  return typeof code === "string" && COUNTRY_CODES.has(code);
}
